### ISSUE TITLE
Release 0.4.6 procedure

### ISSUE THREAD

**Issue by okynos** [Achiefs/fim#111]
# Tasks
- [x] Bump code to 0.4.6
- [x] Create RPM (x86_64) package
- [x] Create RPM (ARM64) package
- [x] Create DEB (x86_64) package
- [x] Create DEB (ARM64) package
- [x] Create MSI package
- [x] Create PKG (x86_64) package
- [x] Create PKG (ARM64) package
- [x] Launch test battery
  - [x] Unit
  - [x] System
  - [x] Static analysis
  - [x] Coverage
- [x] Upload RPMs to LFS
- [x] Upload DEBs to LFS
- [x] Upload MSIs to LFS
- [x] Upload PKGs to LFS
- [x] Create release tag
- [x] Publish release
- [x] Send notifications
- [x] Support users and enjoy 😄
