### ISSUE TITLE
Bump and release 0.3.1

### ISSUE THREAD

**Issue by okynos** [Achiefs/fim#52]
# Tasks
- [x] Bump code to 0.3.1
- [x] Create RPM package
- [x] Create DEB package
- [x] Launch test battery
  - [x] Unit
  - [x] System
  - [x] Static analysis
  - [x] Coverage
- [x] Upload RPM and DEB to LFS
- [ ] Create release tag
- [ ] Publish release
- [ ] Send notifications
- [ ] Support users and enjoy 😄
