### ISSUE TITLE
Release 0.4.1 procedure

### ISSUE THREAD

**Issue by okynos** [Achiefs/fim#74]
# Tasks
- [x] Bump code to 0.4.1
- [x] Create RPM package
- [x] Create DEB package
- [x] Create MSI package
- [x] Launch test battery
  - [x] Unit
  - [x] System
  - [x] Static analysis
  - [x] Coverage
- [x] Upload RPM to LFS
- [x] Upload DEB to LFS
- [x] Upload MSI to LFS
- [x] Create release tag
- [x] Publish release
- [x] Send notifications
- [ ] Support users and enjoy 😄

**Comment by okynos** [comment]
Release finished!

Thanks all.
https://github.com/Achiefs/fim/releases/tag/v0.4.1
